[project]
name = "hackafterdark-nodes"
description = "Custom ComfyUI nodes featuring AfterDark Film Grain & Emulsion, Procedural Film Optics & Light Leaks, Film Halation & Bloom, Film Color Split, Film Aspect Ratio Selector, and Google Gemini Prompter."
version = "1.2.0"
license = "MIT"
requires-python = ">=3.8"
dependencies = ["pyyaml", "requests", "torch", "numpy", "Pillow", "google-generativeai"]

classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
Repository = "https://github.com/hackafterdark/ComfyUI-HackAfterDark-Nodes"
# Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/hackafterdark/ComfyUI-HackAfterDark-Nodes/wiki"
"Bug Tracker" = "https://github.com/hackafterdark/ComfyUI-HackAfterDark-Nodes/issues"

[tool.comfy]
PublisherId = "hackafterdark"
DisplayName = "HackAfterDark Custom Nodes"
Icon = "https://raw.githubusercontent.com/hackafterdark/ComfyUI-HackAfterDark-Nodes/main/icon.png"
requires-comfyui = ">=1.0.0"